# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DockerConainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docker_id', models.CharField(max_length=64)),
                ('docker_user', models.CharField(max_length=64)),
                ('image', models.CharField(default=b'morpheuz/jupyter-notebook-minimal', max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('port', models.IntegerField(default=8000)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
